// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using System.Threading.Tasks;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings
{
    public class MyModuleBindings
    {
        readonly ICloudCodeService k_Service;

        public MyModuleBindings() : this(CloudCodeService.Instance) { }

        public MyModuleBindings(ICloudCodeService service)
        {
            k_Service = service;
        }

        public async Task<string> SayHello(string name)
        {
            return await k_Service.CallModuleEndpointAsync<string>(
                "BounscapeCloud",
                "SayHello",
                new Dictionary<string, object>()
                {
                    {"name", name},
                });
        }

        public async Task<string> GetServerTime()
        {
            return await k_Service.CallModuleEndpointAsync<string>(
                "BounscapeCloud",
                "GetServerTime",
                new Dictionary<string, object>()
                {
                });
        }

        public async Task<string> SetPlayerName(string name)
        {
            return await k_Service.CallModuleEndpointAsync<string>(
                "BounscapeCloud",
                "SetPlayerName",
                new Dictionary<string, object>()
                {
                    {"name", name},
                });
        }
    }
}
